package GUI;

import DAO.TurnoDAO;
import Aux.TurnoListado;
import GUI.EditComponents.EditTurno;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import Logic.Turno;
import Logic.Usuario;

/**
 *
 * @author Alexandro
 */
public class ListarTurnos extends javax.swing.JDialog {

    private TurnoDAO turnoDAO = new TurnoDAO();

    public ListarTurnos(java.awt.Frame parent, boolean modal, Usuario u) {
        super(parent, modal);
        initComponents();
        setTitle("Listado de Turnos");
        configurarTabla();
        cargarTabla();
        if (!u.isAdmin()) {
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
        }
    }

    private void configurarTabla() {
        String[] columnas = {"Hospital", "Depto", "Unidad", "Turno", "Pac. asignados",
            "Pac. atendidos", "Médico", "codMedico", "codUnidad"};
        DefaultTableModel model = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablaTurnos.setModel(model);
        tablaTurnos.getTableHeader().setReorderingAllowed(false);

        tablaTurnos.getColumnModel().getColumn(7).setMinWidth(0);
        tablaTurnos.getColumnModel().getColumn(7).setMaxWidth(0);
        tablaTurnos.getColumnModel().getColumn(7).setWidth(0);
        tablaTurnos.getColumnModel().getColumn(8).setMinWidth(0);
        tablaTurnos.getColumnModel().getColumn(8).setMaxWidth(0);
        tablaTurnos.getColumnModel().getColumn(8).setWidth(0);
    }

    private void cargarTabla() {
        DefaultTableModel model = (DefaultTableModel) tablaTurnos.getModel();
        model.setRowCount(0);
        try {
            ArrayList<TurnoListado> lista = turnoDAO.listarTurnos();
            for (TurnoListado tl : lista) {
                model.addRow(new Object[]{
                    tl.getHospital(), tl.getDepartamento(), tl.getUnidad(),
                    tl.getNumTurno(), tl.getCantPacientes(), tl.getPacientesAtend(),
                    tl.getNombreMedico(), tl.getCodMedico(), tl.getCodUnidad()
                });
            }
        } catch (RuntimeException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTurnos = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaTurnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaTurnos);

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 861, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int filas = tablaTurnos.getSelectedRows().length;
        boolean puedeEliminar = false;
        if (filas == 1) {
            puedeEliminar = true;
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione solo un turno para eliminar.");
        }
        if (puedeEliminar) {
            int fila = tablaTurnos.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) tablaTurnos.getModel();
            String codUnidad = model.getValueAt(fila, 8).toString();
            int numTurno = (int) model.getValueAt(fila, 3);
            int informes = turnoDAO.contarInformesDeTurno(codUnidad, numTurno);
            boolean puedeBorrar = true;
            if (informes > 0) {
                JOptionPane.showMessageDialog(this,
                        "El turno tiene " + informes + " informe(s) asociado(s). Elimínelos primero.");
                puedeBorrar = false;
            }
            if (puedeBorrar) {
                int confirm = JOptionPane.showConfirmDialog(this,
                        "¿Eliminar el turno " + numTurno + " de la unidad " + codUnidad + "?",
                        "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                    try {
                        turnoDAO.eliminarTurno(codUnidad, numTurno);
                        JOptionPane.showMessageDialog(this, "Turno eliminado correctamente.");
                        cargarTabla();
                    } catch (RuntimeException ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int filas = tablaTurnos.getSelectedRows().length;
        boolean puedeEditar = false;
        if (filas == 1) {
            puedeEditar = true;
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione solo un turno para editar.");
        }
        if (puedeEditar) {
            int fila = tablaTurnos.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) tablaTurnos.getModel();
            String codUnidad = model.getValueAt(fila, 8).toString();
            int numTurno = (int) model.getValueAt(fila, 3);
            Turno turno = turnoDAO.obtenerTurno(codUnidad, numTurno);
            if (turno != null) {
                EditTurno dialog = new EditTurno(null, true, turno);
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
                cargarTabla();
            } else {
                JOptionPane.showMessageDialog(this, "Turno no encontrado.");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ListarTurnos dialog = new ListarTurnos(new javax.swing.JFrame(), true, new Usuario(000, "Prueba", "Prueba", "123", true));
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaTurnos;
    // End of variables declaration//GEN-END:variables
}
