/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import DAO.UnidadDAO;
import GUI.EditComponents.EditUnidad;
import java.util.ArrayList;
import Logic.*;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alexandro
 */
public class ListadoUnidad extends JDialog {

    private UnidadDAO unidadDAO = new UnidadDAO();

    public ListadoUnidad(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setTitle("Listado de Unidades");
        initComponents();
        configurarTabla();
        cargarTabla();

    }

    private void configurarTabla() {
        String[] columnas = {"Código", "Nombre", "Ubicación", "Depto"};
        DefaultTableModel model = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablaUnidades.setModel(model);
        tablaUnidades.getTableHeader().setReorderingAllowed(false);
    }

    private void cargarTabla() {
        DefaultTableModel model = (DefaultTableModel) tablaUnidades.getModel();
        model.setRowCount(0);
        ArrayList<Unidad> lista = unidadDAO.listarUnidades();
        for (Unidad u : lista) {
            model.addRow(new Object[]{
                u.getId(),
                u.getName(),
                u.getLocation(),
                u.getCodDpt()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUnidades = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaUnidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaUnidades);

        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int filasSeleccionadas = tablaUnidades.getSelectedRows().length;
        boolean puedeModificar = false;
        if (filasSeleccionadas == 1) {
            puedeModificar = true;
        } else {
            JOptionPane.showMessageDialog(this,
                    "Seleccione solo una unidad para modificar.",
                    "Error", JOptionPane.WARNING_MESSAGE);
        }

        if (puedeModificar) {
            int fila = tablaUnidades.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) tablaUnidades.getModel();
            String codUnidad = model.getValueAt(fila, 0).toString();
            Unidad unidad = unidadDAO.obtenerUnidadPorCodigo(codUnidad);
            boolean unidadExiste = (unidad != null);
            if (!unidadExiste) {
                JOptionPane.showMessageDialog(this,
                        "No se encontró la unidad en la base de datos.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
            if (unidadExiste) {
                EditUnidad dialog = new EditUnidad(null, true, unidad);
                dialog.setLocationRelativeTo(this);
                dialog.setVisible(true);
                cargarTabla();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int filasSeleccionadas = tablaUnidades.getSelectedRows().length;
        boolean puedeEliminar = false;
        if (filasSeleccionadas == 1) {
            puedeEliminar = true;
        } else {
            JOptionPane.showMessageDialog(this,
                    "Seleccione solo una unidad para eliminar.",
                    "Error", JOptionPane.WARNING_MESSAGE);
        }

        if (puedeEliminar) {
            int fila = tablaUnidades.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) tablaUnidades.getModel();
            String codUnidad = model.getValueAt(fila, 0).toString();
            String nombreUnidad = model.getValueAt(fila, 1).toString();

            int medicos = unidadDAO.contarMedicosEnUnidad(codUnidad);
            boolean puedeBorrar = true;
            if (medicos > 0) {
                JOptionPane.showMessageDialog(this,
                        "La unidad \"" + nombreUnidad + "\" tiene " + medicos + " médico(s) asignado(s).\n"
                        + "Elimine primero los médicos de esta unidad.",
                        "Eliminación no permitida", JOptionPane.WARNING_MESSAGE);
                puedeBorrar = false;
            }

            if (puedeBorrar) {
                int confirm = JOptionPane.showConfirmDialog(this,
                        "¿Eliminar la unidad \"" + nombreUnidad + "\" (" + codUnidad + ")?",
                        "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                    try {
                        unidadDAO.eliminarUnidad(codUnidad);
                        JOptionPane.showMessageDialog(this, "Unidad eliminada correctamente.");
                        cargarTabla();
                    } catch (RuntimeException ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListadoUnidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListadoUnidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListadoUnidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListadoUnidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ListadoUnidad dialog = new ListadoUnidad(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaUnidades;
    // End of variables declaration//GEN-END:variables
}
