/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import DAO.DepartamentoDAO;
import GUI.EditComponents.EditDpt;
import javax.swing.table.DefaultTableModel;
import Logic.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexandro
 */
public class ListadoDpt extends javax.swing.JDialog {

    /**
     * Creates new form ListadoDpt
     */
    private DepartamentoDAO departamentoDAO = new DepartamentoDAO();

    public ListadoDpt(java.awt.Frame parent, boolean modal, Usuario u) {
        super(parent, modal);
        initComponents();
        setTitle("Listado de Departamentos");
        configurarTabla();
        cargarTabla();
        if (!u.isAdmin()) {
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
        }
    }

    private void configurarTabla() {
        String[] columnas = {"Código", "Nombre", "ID Hospital"};
        DefaultTableModel model = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablaDepartamentos.setModel(model);
        tablaDepartamentos.getTableHeader().setReorderingAllowed(false);
    }

    private void cargarTabla() {
        DefaultTableModel model = (DefaultTableModel) tablaDepartamentos.getModel();
        model.setRowCount(0);
        ArrayList<Departamento> lista = departamentoDAO.listarDpt();
        for (Departamento d : lista) {
            model.addRow(new Object[]{
                d.getId(),
                d.getName(),
                d.getIdHosp()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDepartamentos = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaDepartamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaDepartamentos);

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int filasSeleccionadas = tablaDepartamentos.getSelectedRows().length;
        boolean puedeModificar = false;
        if (filasSeleccionadas == 1) {
            puedeModificar = true;
        } else {
            JOptionPane.showMessageDialog(this,
                    "Seleccione solo un departamento para modificar.",
                    "Error al escoger departamento", JOptionPane.WARNING_MESSAGE);
        }

        if (puedeModificar) {
            int fila = tablaDepartamentos.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) tablaDepartamentos.getModel();
            String codDpt = model.getValueAt(fila, 0).toString();

            Departamento departamento = departamentoDAO.obtenerDepartamentoPorCodigo(codDpt);
            boolean departamentoExiste = (departamento != null);

            if (!departamentoExiste) {
                JOptionPane.showMessageDialog(this,
                        "No se encontró el departamento en la base de datos.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }

            if (departamentoExiste) {
                EditDpt dialog = new EditDpt(null, true, departamento);
                dialog.setLocationRelativeTo(this);
                dialog.setVisible(true);

                cargarTabla();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int filas = tablaDepartamentos.getSelectedRows().length;
        if (filas != 1) {
            JOptionPane.showMessageDialog(null, "Seleccione solo un Departamento", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            int fila = tablaDepartamentos.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) tablaDepartamentos.getModel();
            String codDpt = model.getValueAt(fila, 0).toString();
            String nombreDpt = model.getValueAt(fila, 1).toString();

            int confirm = JOptionPane.showConfirmDialog(this,
                    "¿Eliminar el departamento \"" + nombreDpt + "\" (" + codDpt + ")?",
                    "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    departamentoDAO.eliminarDepartamento(codDpt);
                    JOptionPane.showMessageDialog(this, "Departamento eliminado correctamente.");
                    cargarTabla();
                } catch (RuntimeException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListadoDpt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListadoDpt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListadoDpt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListadoDpt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ListadoDpt dialog = new ListadoDpt(new javax.swing.JFrame(), true, new Usuario(000, "Prueba", "Prueba", "123", true));
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDepartamentos;
    // End of variables declaration//GEN-END:variables
}
